#include "main.h"
#include "work.h"
#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  struct stateMachine currentState;
  struct stateMachine previousState;
  currentState.gameState = START;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    previousState = currentState;
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
      currentState.gameState = START;
    }
    switch (currentState.gameState) {
      case START:
        currentState = startWork(currentState);
        break;
      case HOLDSTART:
        currentState = holdStartWork(currentState, previousButtons, currentButtons);
        break;
      case INIT:
        currentState = initWork(currentState);
        break;
      case PLAY:
        currentState = playWork(previousState, currentState, currentButtons);
        break;
      case LOSE:
        currentState = loseWork(currentState);
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
